spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: yeo
    password: 6235
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8443

jwt:
  secret: mysecretkey12345678901234567890
  access-token-expire: 3600000 # 1시간